name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Use Python 3.8 for compatibility

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip libssl-dev libffi-dev zlib1g-dev libncurses5 libncursesw5 gcc liblzma-dev libgdbm-dev libnss3-dev libreadline-dev libsqlite3-dev curl libbz2-dev libffi-dev libtool autoconf automake

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: EZIPhishingDetection
        path: bin/*.apk
